[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "snake_game"
version = "0.0.1"

description = "Snake game"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
  'pygame >= 2.3.0',
]
